"use client";

import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { briefQuestions } from "@/lib/mock-data";
import { Sparkles, ChevronRight, ChevronLeft, Check } from "lucide-react";

const sampleBrief = `# Design Brief — Generated by ArchiPro AI

## Project Overview
A **new build residential home** in an **urban** setting with a **contemporary minimalist** aesthetic. The home should accommodate **3 bedrooms** with a strong emphasis on **indoor-outdoor flow** and **natural light**.

## Budget
**$500k – $1M** — this range supports high-quality materials and finishes with room for bespoke elements.

## Design Direction
- Clean lines with an emphasis on horizontal planes
- Neutral material palette: concrete, timber, and glass
- Open-plan living that connects seamlessly to outdoor spaces
- Full-height glazing on north-facing elevations
- Concealed storage throughout to maintain minimal visual clutter

## Recommended Products
- **Engineered Oak Panel** by DuraLux Surfaces — flooring and feature walls
- **Pendant Light — Arc** by Flōra Lighting — dining and kitchen areas
- **Matte Black Pull Handle** by Akaroa Kitchens — joinery throughout
- **Composite Deck Board** by TerraRange — outdoor entertaining

## Suggested Architects
Based on your brief, we recommend exploring work by:
- **Elena Vasquez** (Vasquez Studio) — sustainable residential specialist
- **Oliver Park** (Park Studio) — minimalist urban living expert

## Next Steps
1. Review this brief with your architect
2. Explore tagged products in the ArchiPro library
3. Request quotes from recommended suppliers
4. Schedule a site visit with your preferred studio

---
*Generated by ArchiPro AI — this brief is a starting point for discussion with your design team.*`;

export default function BriefPage() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [generating, setGenerating] = useState(false);
  const [brief, setBrief] = useState<string | null>(null);

  const totalSteps = briefQuestions.length;
  const currentQ = briefQuestions[step];
  const isComplete = step >= totalSteps;

  function selectAnswer(value: string) {
    setAnswers({ ...answers, [currentQ.id]: value });
  }

  function handleGenerate() {
    setGenerating(true);
    setTimeout(() => {
      setBrief(sampleBrief);
      setGenerating(false);
    }, 2000);
  }

  if (brief) {
    return (
      <>
        <PageHeader
          title="Your Design Brief"
          subtitle="Generated by ArchiPro AI based on your preferences."
        />
        <div className="mx-auto max-w-3xl px-6 py-12">
          <div className="rounded-2xl border border-border bg-white p-8">
            <div className="prose prose-neutral max-w-none">
              {brief.split("\n").map((line, i) => {
                if (line.startsWith("# "))
                  return (
                    <h1 key={i} className="text-2xl font-semibold tracking-tight mt-0">
                      {line.replace("# ", "")}
                    </h1>
                  );
                if (line.startsWith("## "))
                  return (
                    <h2 key={i} className="text-lg font-semibold mt-8 mb-3">
                      {line.replace("## ", "")}
                    </h2>
                  );
                if (line.startsWith("- "))
                  return (
                    <p key={i} className="text-sm text-muted ml-4 my-1">
                      &bull; {line.replace("- ", "").replace(/\*\*(.*?)\*\*/g, "$1")}
                    </p>
                  );
                if (line.startsWith("---")) return <hr key={i} className="my-6 border-border" />;
                if (line.startsWith("*"))
                  return (
                    <p key={i} className="text-xs text-muted italic mt-4">
                      {line.replace(/\*/g, "")}
                    </p>
                  );
                if (line.match(/^\d\./))
                  return (
                    <p key={i} className="text-sm text-muted ml-4 my-1">
                      {line.replace(/\*\*(.*?)\*\*/g, "$1")}
                    </p>
                  );
                if (line.trim() === "") return <div key={i} className="h-2" />;
                return (
                  <p key={i} className="text-sm leading-relaxed text-muted">
                    {line.replace(/\*\*(.*?)\*\*/g, "$1")}
                  </p>
                );
              })}
            </div>
          </div>
          <div className="mt-8 text-center">
            <button
              onClick={() => {
                setBrief(null);
                setStep(0);
                setAnswers({});
              }}
              className="rounded-full border border-border px-6 py-2.5 text-sm transition-colors hover:bg-card"
            >
              Start over
            </button>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader
        title="AI Design Brief Generator"
        subtitle="Answer a few questions and our AI will create a personalised design brief for your project."
      />
      <div className="mx-auto max-w-2xl px-6 py-16">
        {/* Progress */}
        <div className="mb-12">
          <div className="flex justify-between text-xs text-muted mb-2">
            <span>
              {isComplete ? "Ready to generate" : `Question ${step + 1} of ${totalSteps}`}
            </span>
            <span>{Math.round(((isComplete ? totalSteps : step) / totalSteps) * 100)}%</span>
          </div>
          <div className="h-1 rounded-full bg-card">
            <div
              className="h-1 rounded-full bg-foreground transition-all duration-500"
              style={{
                width: `${((isComplete ? totalSteps : step) / totalSteps) * 100}%`,
              }}
            />
          </div>
        </div>

        {!isComplete ? (
          <>
            <h2 className="text-2xl font-semibold tracking-tight">
              {currentQ.question}
            </h2>
            <div className="mt-8 grid gap-3 sm:grid-cols-2">
              {currentQ.options.map((opt) => (
                <button
                  key={opt}
                  onClick={() => selectAnswer(opt)}
                  className={`rounded-2xl border px-5 py-4 text-left text-sm transition-all ${
                    answers[currentQ.id] === opt
                      ? "border-foreground bg-foreground text-white"
                      : "border-border hover:border-foreground/30"
                  }`}
                >
                  {opt}
                </button>
              ))}
            </div>
            <div className="mt-10 flex justify-between">
              <button
                onClick={() => setStep(Math.max(0, step - 1))}
                disabled={step === 0}
                className="flex items-center gap-1 text-sm text-muted transition-colors hover:text-foreground disabled:opacity-30"
              >
                <ChevronLeft size={14} /> Back
              </button>
              <button
                onClick={() => setStep(step + 1)}
                disabled={!answers[currentQ.id]}
                className="flex items-center gap-1 rounded-full bg-foreground px-6 py-2 text-sm text-white transition-opacity hover:opacity-80 disabled:opacity-30"
              >
                Next <ChevronRight size={14} />
              </button>
            </div>
          </>
        ) : (
          <div className="text-center">
            <div className="mx-auto mb-8 flex h-16 w-16 items-center justify-center rounded-full bg-card">
              <Check size={24} />
            </div>
            <h2 className="text-2xl font-semibold tracking-tight">
              All set!
            </h2>
            <p className="mt-3 text-base text-muted">
              We have everything we need. Generate your personalised design
              brief now.
            </p>
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="mt-8 inline-flex items-center gap-2 rounded-full bg-foreground px-8 py-3 text-sm font-medium text-white transition-opacity hover:opacity-80 disabled:opacity-60"
            >
              {generating ? (
                <>
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={16} />
                  Generate Brief
                </>
              )}
            </button>

            {/* Summary */}
            <div className="mt-12 rounded-2xl border border-border p-6 text-left">
              <h3 className="mb-4 text-sm font-semibold">Your answers</h3>
              {briefQuestions.map((q) => (
                <div key={q.id} className="flex justify-between border-b border-border py-2 last:border-0 text-sm">
                  <span className="text-muted">{q.question}</span>
                  <span className="font-medium">{answers[q.id] || "—"}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </>
  );
}
